### ISSUE TITLE
NEW SITE: Change Curators rights for modification 

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#133]
Currently, a curator declared as admin of an ontology (e.g. rice) can login  and then submit a change to any ontology - is this what we wanted? .(see screenshot) The fact that the change is submitted for approval prevent changes being directly made by other users so this should be fine. 
Then the submission is reviewed by the power users (technical coordinators) but is it also posted for review to the curator of the ontology subject to the modification submission?
![Capture d’écran 2021-06-23 à 13 33 54](https://user-images.githubusercontent.com/1417541/123090552-91831780-d428-11eb-9291-6517a9aff494.png)

**Comment by qlands** [comment]
That is normal. The user that can login into the website (Admins or curators). Curators can submit a change for revision and will appear to power users for review. But also it will appear to the user that made suggested the change (as the image shows it) because the user can decide to Discard the change (e.g., It was a mistake). Power users can Approve or Reject the change.

> Currently, a curator declared as admin of an ontology (e.g. rice) can login and then submit a change to any ontology - is this what we wanted?
Users of the website will be power users or curators. Meaning if you are able to log in is because you can curate or can administer the site. So this is in my view the normal funcionality.
