### ISSUE TITLE
NEW SITE

### ISSUE THREAD

**Issue by ShresthaR** [bioversity/Crop-Ontology#153]
Hello Everyone, 
Thanks so much for the new website, congratulations ! I am attaching the document where you can find some minor feedback that observed as the user when I was using the website. Thank you all.
[CO_New_Website.docx](https://github.com/bioversity/Crop-Ontology/files/6773220/CO_New_Website.docx)

**Comment by marieALaporte** [comment]
Hi @ShresthaR.
The issue with the icons has been fixed, as well as the tree issues. That will be available with the next release of the website.

The things that are still pending are:
vi)	Cancel button is not available once Edit terms is clicked 
vii)	Comments/notes typed in the ‘Notes for reviewers’ section was not saved. I did not want to make any changes in the content of selected traits for text. So, I used this section but the comment was not saved and got the message below. There was no ‘cancel’
viii)	It would be great help for the users if there is a way to navigate me to previous working page. For example, if I were in the wheat trait ontology page, I would want to go to this page directly rather than click to home page and start overall the process reselecting the ontology from the list.
All those points are link to the reviewer/curator part of the site. I will thus recreate separate issues from them, after checking with @elizabetharnaud that some comments are not already reported. 

I am thus closing this issue, with is generic
