### ISSUE TITLE
Sync problem with OLS

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#194]
Sync is suspended

**Comment by marieALaporte** [comment]
Email from Henriette Harmse:
The main issue is that OLS4 uses JSON configuration instead of YAML. In general this change has no impact on our users. It just means you should convert the existing YAML file to JSON. We tried to do this for your [YAML configuration](https://cropontology.org/metadata), but your YAML configuration does not parse in a YAML parser.

If you can provide us with a JSON file for your crop ontologies, we will gladly add it to our configuration for OLS4, assuming they load successfully on OLS4.

We will be shutting down OLS3 by the end of the year and OLS3 can no longer be updated due to scalability issues. Thus, we strongly recommend migrating to OLS4.

**Comment by marieALaporte** [comment]
OLS [link](https://www.ebi.ac.uk/ols/index)

**Comment by marieALaporte** [comment]
should be fixed when server will be updated
