### ISSUE TITLE
Why using SKOS instead of OWL for OBO conversion?

### ISSUE THREAD

**Issue by ansell** [bioversity/Crop-Ontology#30]
The standard OBO to RDF converter uses OWL as its output schema, rather than SKOS. What is the advantage of using SKOS for Crop Ontology RDF downloads?

In the meantime it is fairly simple to download the OBO version and run the OBO2OWL converters on it, but just wondering why SKOS has been chosen.

**Comment by lmatteis** [comment]
We decided to use SKOS because it's better fit for taxonomies. Crop Ontology is more of a taxonomy of traits and breeding methodologies, rather than a structure made of Classes and Properties (OWL).

Nonetheless I'm still a bit confused regarding the entire OBO format. Some [people seem to think](http://answers.semanticweb.com/questions/21570/is-obo-compatible-with-the-linked-data-initiative/21573) that it's not a supported format and frankly I'm a bit puzzled how it helps with interoperability given it doesn't use HTTP URIs and such. Maybe I'm missing something.

Anyway, Crop Ontology will need to continue supporting OBO and we plan of having a version available also for SKOS that maps the relevant OBO terms into SKOS terms.

**Comment by ansell** [comment]
Given that the new OBO2OWL converter was recently migrated into the OWLAPI codebase, I don't think OBO and OWL are going to be delinked too soon.

However, it would be nice to have an equivalent OBO to SKOS converter that you are using available for comment to contrast with it.

Personally, I want to use Crop Ontology terms in OWL, so I will stick to the OBO->OWL method, but SKOS is definitely used by some people out there so good to support it also.

May want to highlight in the interface that the RDF download is SKOS and not OWL that they may be expecting.
