### ISSUE TITLE
Some calls to get-ontology-roots have oboBlobKey as an object with the key "undefined"

### ISSUE THREAD

**Issue by ansell** [bioversity/Crop-Ontology#33]
Some calls to get-ontology-roots give back JSON results that have the oboBlobKey as an object with the string "undefined" as the key, instead of directly linking to the actual oboBlobKey value string.

For example, the "SOY" ontology has an output that looks roughly like:

```
{id=SOY:0000000, name={"undefined":"Soybean Growth and Trait Ontology V2.0 revision 7"}, oboBlobKey={"undefined":"AMIfv97Y5v7rvpwlS_EL0naInKJz80FbHPpRB_1NP-KG_cNshPzazlUB1eCIPEcnFP6-lHNImtxKTKCxZp1HkVXRdWhVrbEcmvsxuCZQwykCwWekcq-qtTLL4ubTa_xc1VG9gMTb6t2Mw50vv5qhISzcOHgnmvH8mAo8kbHXUw2N2yHoid2i_mWHO51zdsn3UcsI1m1Ra_XM"}, excelBlobKey=[Ljava.lang.Object;@60461}
```

Not sure what the reason for the excelBlobKey being like that is, but it may also be an issue for people looking for the excel representation in that case.

**Comment by lmatteis** [comment]
Indeed it's because some ontologies are uploaded directly as a taxonomy (RDF/SKOS) and we still weren't able to convert into OBO. So essentially OBO to RDF is fine, but not the other way around. There are some conceptual differences within the format of OBO that doesn't make this an easy task. Can you use the RDF version and try and convert that into OWL?

**Comment by ansell** [comment]
I may be able to develop a translator from SKOS to OWL if necessary, but it isn't high on my todo list right now, as the OBO to OWL converter works fairly well. However, if I end up using one of the ontologies that is native SKOS, the todo list may change.

**Comment by lmatteis** [comment]
May I ask in what application you're using OWL in? What specifically are you describing using OWL? Which system?

**Comment by ansell** [comment]
I think Xavier Sirault ( @DrXav ) presented our software, PODD, at ESWC last year and you may have been there.

https://github.com/podd/podd-redesign

The architecture does not prevent the use of rules to support SKOS, but it is currently implemented solely using OWL.

We are currently describing plant phenomics experiments.

**Comment by marieALaporte** [comment]
As a SKOS document is defined as an OWL ontology (skos:conceptScheme and skos:concept are defined as OWL classes, and the different skos properties are defined as OWL annotation or object properties), maybe the simplest way to use a SKOS file would be to add these definition elements to the all the CO SKOS concepts and properties. 
For instance, a SKOS concept from CO could be exeplicitely defined as xxx rdf:type owl:Class. Doing this, all the CO concepts will be managed as owl:Class in your system.
For properties, this could be a little more tricky. A reason why SKOS is less formal that OWL is because the broader/narrower relationships do not imply the same semantics than owl:subClass (subsumption). Regarding this issue, we have tried to use the broader/narrower relationships in CO as if we had used the sub/super classes in OWL. This has been done with the purpose of facilitating the matching between the Crop Ontology and an OWL ontology, for future evolution of the Crop Ontology.
All of this could be managed very easily using OWL API (if I remember correctly the talk of Xavier, PODD uses OWL API). 

But anyway, in the next version of the Crop Ontology website, we will still provide up to date OBO files to users.
