### ISSUE TITLE
Search feature improvement

### ISSUE THREAD

**Issue by gubi** [bioversity/Crop-Ontology#60]
_The terms that the research function yields are all mixed together. It would be useful to add tags to the research outputs such as “Trait”, “Method”, “Scale”, “Variable”, “Ontology name”._

**Comment by gubi** [comment]
This feature will be added to the new interface

**Comment by gubi** [comment]
Do you like this new layout?

![new crop ontology interface](https://user-images.githubusercontent.com/746559/46341579-cc214200-c638-11e8-8ed0-5580a755e4ce.jpg)

**Comment by marieALaporte** [comment]
I think the ontologies should be central in the website. 
Could you switch the left part and the right part? The news are relevant information but are not the main content of the Crop Ontology website

**Comment by gubi** [comment]
As requested

![new crop ontology interface_reverted](https://user-images.githubusercontent.com/746559/46464713-4e3f7100-c7c7-11e8-8bfd-8f2a84a80ae8.jpg)

**Comment by elizabetharnaud** [comment]
Hi Alessandro ! Very nice looking ! I like the second one because like Marie,I think the Crop Ontology is central. the RSS feed with the CO community news is nice too. I just wonder where the ifnormation  from the grey space on the original Co tool web site is? I mean the information on how to submit a Trait Dictionary (download TD template, get crop codes, etc) ? the fact that any Ontology uploaded here is automatically push to the Planteome Github and the Ontology Look up service?

**Comment by gubi** [comment]
Hi,
sorry I missed the most important area... just to not subtract space on the search area, we can place the grey box at the top of ontologies column.
Regarding the synchronization, I think is already reported in #62 and - as discussed today with @marieALaporte - I'll start my development on Planteome and Dataverse from the next week

**Comment by gubi** [comment]
Sorry,
Dataverse fixes are from the next week, Planteome (#62) is *this* week, instead :)
